In [11]:
from faker import Faker
import random
import json
import pandas as pd

In [12]:
# Initialize faker
fake = Faker()

# Predefined membership types and statuses
membership_types = ["Basic", "Standard", "Premium"]
subscription_statuses = ["Active", "Inactive", "Suspended"]

# Function to generate a fake gym customer
def generate_gym_customer(id):
    return {
        "id": id,
        "full_name": fake.name(),
        "email": fake.email(),
        "phone_number": fake.phone_number(),
        "age": random.randint(18, 65),
        "gender": random.choice(["Male", "Female", "Other"]),
        "country": fake.country(),
        "join_date": fake.date_between(start_date='-3y', end_date='today').isoformat(),
        "membership_type": random.choice(membership_types),
        "subscription_status": random.choice(subscription_statuses),
        "last_check_in": fake.date_between(start_date='-30d', end_date='today').isoformat(),
        "weight_kg": round(random.uniform(50, 120), 1),
        "height_cm": round(random.uniform(150, 200), 1)
    }

# Generate 100 records
gym_customers = [generate_gym_customer(i+1) for i in range(100)]

# Convert to DataFrame for preview
df_gym = pd.DataFrame(gym_customers)
df_gym.head()

,id,full_name,email,phone_number,age,gender,country,join_date,membership_type,subscription_status,last_check_in,weight_kg,height_cm
0,1,Anthony Mullins,victoriadavidson@example.org,+1-776-682-5529x364,49,Male,Bahamas,2023-06-10,Standard,Suspended,2025-02-26,101.9,198.5
1,2,Samantha Vargas,carrie92@example.org,5855564825,28,Male,Malawi,2023-07-15,Basic,Active,2025-03-18,75.1,191.3
2,3,Austin Martin,jaime44@example.com,001-851-245-9736x392,39,Female,American Samoa,2023-02-18,Basic,Active,2025-03-23,101.6,192.7
3,4,Pamela Archer,lpadilla@example.net,(483)262-4219,28,Male,Japan,2025-01-14,Premium,Suspended,2025-03-09,118.6,172.5
4,5,Becky Thomas DVM,michael70@example.net,984.637.1740,30,Male,Mauritania,2024-06-07,Standard,Suspended,2025-03-22,67.8,195.8

In [13]:
# Save as a JSON file
output_file = "gym_customers.json"
with open(output_file, "w") as f:
    json.dump(gym_customers, f, indent=4)

print(f"✅ JSON file saved as: {output_file}")

✅ JSON file saved as: gym_customers.json